--- #YAML:1.0
name:               Test-RemoteServer
version:            0.5
abstract:           Test routines for remote servers.
author:
    - Steve Kemp <steve@steve.org.uk>
license:            perl_5
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Net::DNS:       ~
    Test::Builder:  ~
    Test::More:     ~
resources:
    bugtracker:  https://github.com/skx/Test-RemoteServer/issues
    homepage:    https://github.com/skx/Test-RemoteServer/
    license:     http://dev.perl.org/licenses/
    Rep_mirror:  http://git.steve.org.uk/cpan/Test--RemoteServer
    repository:  https://github.com/skx/Test-RemoteServer.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
